services:
  - type: web
    name: curriculum-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run serve:ssr:Curriculum
    envVars:
      - key: NODE_VERSION
        value: 18.19.1