export enum TipoExperiencia {
    PROYECTO_PERSONAL = 'PROYECTO_PERSONAL',
    TRABAJO_LABORAL_COLABORATIVO = 'TRABAJO_LABORAL_COLABORATIVO',
    APORTE_CODIGO_ABIERTO = 'APORTE_CODIGO_ABIERTO',
    PRACTICA_PROFESIONAL = 'PRACTICA_PROFESIONAL',
    TRABAJO_LABORAL_FREELANCE = 'TRABAJO_LABORAL_FREELANCE'
}